---
- name: update previous release to newest release
  hosts: all
  tasks:
    - name: set current github commit as version when available
      set_fact:
        paperlessng_version: "{{ lookup('env', 'TARGET_GITHUB_SHA') | default('master', True) }}"
    - name: update to newest paperless-ng release
      include_role:
        name: ansible
