- name: install previous release
  hosts: all
  tasks:
    - name: set previous version as installation target
      set_fact:
        paperlessng_version: latest

    - name: install previous paperless-ng release
      include_role:
        name: ansible
